# Generated by Django 5.2.2 on 2025-08-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_razorpay_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
