# Generated by Django 5.2.2 on 2025-06-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_categories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='title',
        ),
    ]
