# Generated by Django 5.2.2 on 2025-06-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_color_size_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, help_text='e.g. #FF5733', max_length=7),
        ),
    ]
