# Generated by Django 5.2.2 on 2025-10-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
