# Generated by Django 5.2.2 on 2025-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, upload_to='offer_images'),
        ),
    ]
