# Generated by Django 5.2.2 on 2025-10-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
