# Generated by Django 5.2.2 on 2025-10-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
    ]
